[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
RustToolChains = "e9dc52e2-edb8-4742-9783-5e542d30dbb5"

[sources]
RustToolChains = {rev = "main", url = "https://github.com/AtelierArith/RustToolChains.jl.git"}
